### ISSUE TITLE
Problem resolving dependency in dev-site

### ISSUE THREAD

**Issue by m-samkc** [cerner/terra-dev-site#100]
# Bug Report

## Description
I'm trying to make use of [terra-dev-site](https://github.com/cerner/terra-dev-site) for npm project documentation purpose. Followed the instructions from [getting started](https://engineering.cerner.com/terra-dev-site/#/getting-started/terra-dev-site/getting-started). However once the compilation is successful, navigating to localhost:8080 throws an **exception** as mentioned below,
```
client:167 ../extensible-app-framework-ui/node_modules/terra-navigation-side-menu/node_modules/terra-list/lib/List.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/ms025226/Documents/New_HealtheLife/extensible-app-framework-ui/node_modules/terra-navigation-side-menu/node_modules/terra-list/lib/List.js'
 @ ../extensible-app-framework-ui/node_modules/terra-navigation-side-menu/lib/NavigationSideMenu.js 25:17-38
 @ ../extensible-app-framework-ui/node_modules/terra-application-layout/lib/menu/RoutingMenu.js
 @ ../extensible-app-framework-ui/node_modules/terra-application-layout/lib/ApplicationLayout.js
 @ ../extensible-app-framework-ui/lib/utils/EAFtoTerraConverter.js
 @ ../extensible-app-framework-ui/lib/index.js
 @ ./src/components/layouts/FullLayout.js
 @ ./src/components/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./example/static/mockClientConfigs.js ./example/static/variables.css ./src/index.js
errors @ client:167 
```

## Steps to Reproduce
1. Follow instructions from [getting started](https://engineering.cerner.com/terra-dev-site/#/getting-started/terra-dev-site/getting-started)
2. Add script `"devsite": "tt-serve"` in project package.json 
3. Run `yarn devsite`
4. Compilation result 
```
[./node_modules/babel-polyfill/lib/index.js] 833 bytes {babel-polyfill}
[./node_modules/core-js/fn/regexp/escape.js] 108 bytes {babel-polyfill}
[./node_modules/raf/index.js] 1.89 KiB {raf}
[./node_modules/raf/polyfill.js] 25 bytes {raf}
[./node_modules/react-dom/index.js] 1.33 KiB {terra-dev-site}
[./node_modules/terra-dev-site/lib/Index.js] 1.42 KiB {terra-dev-site}
[./node_modules/webpack-hot-client/client/hot.js] (webpack)-hot-client/client/hot.js 4.91 KiB {raf}
[./node_modules/webpack-hot-client/client/index.js?47ddf97a-f83f-4873-9a41-bd9fd5b5d42b] (webpack)-hot-client/client?47ddf97a-f83f-4873-9a41-bd9fd5b5d42b 2.47 KiB {raf}
[./node_modules/webpack-hot-client/client/log.js] (webpack)-hot-client/client/log.js 2.4 KiB {raf}
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {raf} {babel-polyfill} {terra-dev-site}
[./node_modules/xfc/lib/index.js] 490 bytes {terra-dev-site}
[1] multi webpack-hot-client/client?47ddf97a-f83f-4873-9a41-bd9fd5b5d42b raf/polyfill 40 bytes {raf}
[2] multi babel-polyfill 28 bytes {babel-polyfill}
[3] multi ./node_modules/terra-dev-site/lib/Index 28 bytes {terra-dev-site}
    + 1134 hidden modules
ℹ ｢wdm｣: Compiled successfully.
```
5. Navigate to http://localhost:8080/ > More Tools > Dev Tool
6. Verified node_modules/terra-navigation-side-menu/node_modules/terra-list/lib/ doesn't have List.js 

## Additional Context / Screenshots
![screen shot 2018-08-17 at 4 11 58 pm](https://user-images.githubusercontent.com/38563089/44289108-71728900-a238-11e8-8c25-d8d50d31fef6.png)

## Environment

* Component Name and Version: ^2.2.0
* Browser Name and Version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Node/npm Version: v8.9.2
* Webpack Version: 3.11.0 ( from yarn.lock )
* Operating System and version (desktop or mobile): macOS High Sierra

**Comment by bjankord** [comment]
Worked with @m-samkc, this ended up being a compat issue between using v2 terra-dev-site, which uses webpack v4, with a project already using webpack v3.
