### ISSUE TITLE
Update dependencies to latest stable releases

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-dev-site#103]
# Feature Request

## Description
Look through this list and see if we can update to latest stable releases of any dependencies we are behind on: https://david-dm.org/cerner/terra-dev-site

**Comment by emilyrohrbough** [comment]
Update terra-dev-site to use non-deprecated packages: `terra-app-delagate` && `terra-form`

![capture1](https://user-images.githubusercontent.com/14099737/51580647-d470e780-1e8a-11e9-8ea3-dc3af9872288.PNG)
