### ISSUE TITLE
Support MDX format

### ISSUE THREAD

**Issue by nickpith** [cerner/terra-dev-site#110]
# Feature Request

## Description
As a developer, I would really like to use something like [MDX](https://mdxjs.com/) to support writing component documentation so that I can simplify my documentation and move my documentation to live alongside my component source.

## Additional Context / Screenshots
Here are some projects that utilize MDX:
* https://www.docz.site/
* https://compositor.io/x0/
  * In particular, the live code editor in https://compositor.io/x0/MDX example seems very appealing because one of the biggest things I want to do with going thru the Terra documentation is modify the examples to test them out. 
* https://github.com/ChristopherBiscardi/gatsby-mdx

**Comment by bjankord** [comment]
Currently, we use JSX files to generate the doc pages which allow users the ability to import markdown files. MDX would inverse this to a file that is markdown, which allows users to import react components.

I could see MDX files being added in addition to the current JSX file support in regards to the auto doc generation. Currently, we generate routes based on the presence of files in specific directories with an extension of `.doc.jsx` or `test.jsx`.

This could likely be expaned to look for `.doc.mdx` and `.test.mdx`. Would need to figure out how we want to resolve the issue when both `foo.doc.jsx` and `foo.doc.mdx` exist in the same directory.

**Comment by mjhenkes** [comment]
resolved with https://github.com/cerner/terra-dev-site/pull/211
