### ISSUE TITLE
Question on Intended Navigation Focus/Scroll Behavior

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#133]
# Description
The extensions area of the navigation menu receives focus, when the screen size is small enough to 'hide' the navigation menu. When the extensions menu has the focus, you are unable to scroll through along list of navigation items until you tab or click in the navigation menu region. Not sure if this is intended behavior.

## Additional Context / Screenshots
https://cl.ly/f65e43a94ebc

In the attached gif, I attempt to scroll after opening navigation. Once I tab (hard to see, but the back button will gain focus), I am then able to scroll.

**Comment by mjhenkes** [comment]
The extensions section will be removed in v5 of terra-dev-site
