### ISSUE TITLE
Remove Global Wdio Refresh

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#136]
# Feature Request

## Description
Webdriver tests are slower 🐌than they should be because our [global before hook performs a `browser.refresh()`](https://github.com/cerner/terra-dev-site/blob/master/config/wdio/wdio.conf.js#L24-L29) which 
1. slows down tests significantly
2. increased test flakiness as the selenium grid session is terminated and a new request is made for each test `describe` block.

This global hook also enabled tests to be written poorly because the refresh will automatically clean up the current page's state, when tests should be working through a workflow, not a single page's state. _IF_ a refresh is needed (which should be infrequent) it should be manually triggered by the test itself.

Here is a video showing the a test run using the current configuration and then a test run that has removed this configuration: https://cl.ly/7a7d955aaa8e.

Removing this is non-passive and would break tests....An option could be to add a process.env hook for now to toggle this global hook. This be used by people if they would like to start writing smarter, faster tests!

```js
  beforeHook() {
    if(!process.env.DISABLE_DEFAULT_REFRESH) {
      global.browser.refresh();
    }
  },
```

**Comment by yuderekyu** [comment]
![woah](https://media.giphy.com/media/7rj2ZgttvgomY/giphy.gif)
