### ISSUE TITLE
Remove terra-app-delegate dependency

### ISSUE THREAD

**Issue by bjankord** [cerner/terra-dev-site#138]
# Issue Description
When installing terra-dev-site v3.0.0 with the latest major release of terra components (e.g. terra-base 4.0.0), the following warning is generated:

```
warning "terra-dev-site > terra-app-delegate > terra-doc-template@1.20.0" has incorrect peer dependency "terra-base@^3.12.0".
```

With terra-dev-site including terra-app-delegate as a dependency, terra-app-delegate pulls in older versions of components that have a peer dependency on a lower version of terra-base compared to the latest stable release and produce the warning above on npm install.

This warning could cause confusion for developers.

**Comment by emilyrohrbough** [comment]
@bjankord Which command / tool did you use to see this nested error? Or which npm version are you on?

**Comment by bjankord** [comment]
This error message was from running yarn install. A similar error message can be seen when running npm install.

```
npm WARN terra-doc-template@1.23.0 requires a peer of terra-base@^3.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN terra-form@2.10.0 requires a peer of terra-base@^3.7.0 but none is installed. You must install peer dependencies yourself.
```

If you run the following commands, you'll see npm peer dependency warnings
* `mkdir test-directory`
* `cd test-directory`
* `npm init` fill out the prompt to generate a package.json file
* `npm install terra-dev-site terra-base react react-dom` 
  * you can replace this command with `yarn install terra-dev-site terra-base react react-dom` instead to see yarn peer dependency warning.

The main concern I have is around users not understanding why it's warning about needing an older version of terra-base but none was installed. terra-app-delegate doesn't seem to be needed with terra-dev-site anymore since terra-app-delegate was deprecated.

**Comment by bjankord** [comment]
Talked in scrum, planning to treat this as a minor version bump.
