### ISSUE TITLE
Add Option For Generated Config of Repo-installed Packages

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#14]
# Issue Description
Currently for terra-ui.com and coming theming repos, the desired component config will be need to build the sites. An option needs added to indicate `node_module/{terra-core, terra-framework, terra-clinical, terra-consumers}` should be appended to the search patterns. This reduces the need to copy and paste custom regex across repos. 

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by mjhenkes** [comment]
resolved
