### ISSUE TITLE
Reduce Number of Places Locale Config is Defined

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#151]
# Feature Request

## Description
To remove the number of places locales need to be defined in a node project that uses terra-dev-site, we should update terra-dev-site to use the `terraI18n.config.js` locales or fallback to the default locales? otherwise we project need to update locale config in `terraI18n.config.js` and in `terra-dev-site/site.config.js`.

### Expected
Defined one time in `terraI18n.config.js`
```js
const i18nConfig = {
  locales: ['en', 'en-AU', 'en-GB', 'en-US', 'de', 'es', 'fr', 'pt'],
};

module.exports = i18nConfig;
```

### Current
Defined in `dev.site.config` and `terraI18n.config.js`
#### dev.site.config
```js
const siteConfig = {
  appConfig: {
     // my_config
     locales: ['en', 'en-AU', 'en-GB', 'en-US', 'de', 'es', 'fr', 'pt'],
  },
};

module.exports = siteConfig;
```

#### terraI18n.config.js
```js
const i18nConfig = {
  locales: ['en', 'en-AU', 'en-GB', 'en-US', 'de', 'es', 'fr', 'pt'],
};

module.exports = i18nConfig;
```

**Comment by mjhenkes** [comment]
I believe this could be easily done now due to this change:
https://github.com/cerner/terra-toolkit-boneyard/blob/master/config/webpack/webpack.config.js#L143
