### ISSUE TITLE
Remove XFC Dependency & Provider Initialization

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#158]
# Feature Request

## Description
Dev site defined `xfc` as a dependency and then initialized the XFC Provider by default. Most sites do not need this--this had accidentally been included because terra-core & terra-ui needs and XFC provider to correctly load the embedded-content-consumer examples.

Remove:
- https://github.com/cerner/terra-dev-site/blob/master/package.json#L109
- https://github.com/cerner/terra-dev-site/blob/master/src/Index.jsx#L11-L14

**Comment by mjhenkes** [comment]
Resolved with v5
