### ISSUE TITLE
 wdio tests failing at package level

### ISSUE THREAD

**Issue by pranav300** [cerner/terra-dev-site#167]
# Bug Report

## Description
When running wdio test on `terra-notification-dialog` there are 46 test cases failing on the master, after deleting all the reference screenshots and running the wdio test on it, there are 7 test cases failing with only for large being generated.

## Steps to Reproduce
1. Run wdio inside terra-notification dialog.

## Additional Context / Screenshots
These are the failing cases when I deleted the reference folder.
<img width="1680" alt="Screen Shot 2019-05-23 at 10 46 10 AM" src="https://user-images.githubusercontent.com/29273628/58227803-05363000-7d4a-11e9-8520-1af475a4f9bf.png">

Reference folder after the test finishes.
<img width="480" alt="Screen Shot 2019-05-23 at 10 47 22 AM" src="https://user-images.githubusercontent.com/29273628/58227822-1a12c380-7d4a-11e9-811c-4b9d4354749d.png">

## Expected Behavior
It should pass all the wdio tests.

## Environment

* Component Name and Version: terra-notification-dialog 3.1.0.
* Node/npm Version: Node 8.

## Mentions
@emilyrohrbough

**Comment by emilyrohrbough** [comment]
This is an issue where wdio tests are not behaving as expected when running from the package-level.

**Comment by emilyrohrbough** [comment]
current work around is to run the test from the root directory like:
```
npm run wdio -- --spec packages/terra-notification-dialog/tests/wdio/notification-dialog-spec.js
```

**Comment by bjankord** [comment]
We recommend using the temporary workaround for now.

**Comment by emilyrohrbough** [comment]
@mjhenkes  Made changes with v6 consumption in terra repos that resolves this issue. 👍
