### ISSUE TITLE
v6 Site Search Keyboard A11y

### ISSUE THREAD

**Issue by dev-cprice** [cerner/terra-dev-site#178]
# Feature Request

## Description

It would be nice to auto focus on the search field when opening the site search modal so I can immediately start typing.

It would also be nice to have arrow key (up/down) functionality to quickly select items in the search results list.

## Additional Context / Screenshots
When first opening the site search modal, focus is immediately moved to the search field:
![image](https://user-images.githubusercontent.com/34115417/62248156-0d939280-b3ad-11e9-96ce-648e8f79212f.png)

Pretend that I can browse the search list via up/down arrows:
![image](https://user-images.githubusercontent.com/34115417/62248181-1edc9f00-b3ad-11e9-9723-db87314ab581.png)

**Comment by bjankord** [comment]
@scottwilmarth Any thoughts on this from an accessibility perspective.

**Comment by bjankord** [comment]
Talked with Scott and Emily about this, they are ok with shifting focus to this search input when the modal opens, but they would not recommend this pattern for more complex modals.

**Comment by mjhenkes** [comment]
Resolved as far as we're going to.
