### ISSUE TITLE
Secondary Nav Scroll Restoration

### ISSUE THREAD

**Issue by dev-cprice** [cerner/terra-dev-site#187]
# Feature Request

## Description

It would be nice if the scroll position in the secondary nav always matched where you were in the content. Being as this is secondary nav, I know this can get complicated quickly (and this really applies mostly to terra-ui). However!..

As an example, let's say you navigate to <https://engineering.cerner.com/terra-ui/components/terra-form-select/form-select/select> (e.g. clicking on that link instead of navigating manually starting from [terra-ui](https://engineering.cerner.com/terra-ui))

### Current Behavior

Currently, the secondary nav behaves like:

![image](https://user-images.githubusercontent.com/34115417/63468086-980b6700-c42c-11e9-8a1d-ca8f99048fe1.png)

where the nav doesn't scroll to your current location.

### Ideal Behavior

Ideally, it would behave like:

![image](https://user-images.githubusercontent.com/34115417/63468116-aa85a080-c42c-11e9-8535-f654e539e828.png)

where it automatically scrolls to the current location (implying it hooks into browser history too, like [react-router scroll restoration](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md#scroll-restoration))

**Comment by gabeparra01** [comment]
@mjhenkes I can work on this task

**Comment by mjhenkes** [comment]
@gabeparra01 that would be great.
