### ISSUE TITLE
Fix Home Page / Add Markdown Support

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#19]
# Issue Description
When adding Markdown files to Site with anchor links, instead of following the anchor link path, the index page is rendered.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
When using a markdown file, you would expect to stay within the same page.

**Comment by mjhenkes** [comment]
Resolved with v6
