### ISSUE TITLE
Terra-navigation-prompts cause browser alerts to fire when reloading urls which timeout our tests

### ISSUE THREAD

**Issue by po016255** [cerner/terra-dev-site#220]
# Bug Report

## Description
Terra-dev-site uses ApplicationBase from terra-application.  Application base has undocumented functionality where it will display an unsaved changes browser alert popup when trying to reload a page that has a NavigationPrompt from terra-navigation-prompt rendered as a child.  This alert popup is tied to the beforeunload event.  ApplicationBase has a prop to disable this feature, but terra-dev-site is leaving it enabled by default.    [This is the prop comment for browser alerts in ApplicationBase](https://github.com/cerner/terra-application/blob/6785ac4fa8b2e82096c6a0e0ec10819f43ad932c/src/application-base/ApplicationBase.jsx#L59).  

[This is where terra-dev-site is using ApplicationBase and where it can set the unloadPromptIsDisabled prop to disable these alerts.](https://github.com/cerner/terra-dev-site/blob/fa1700474d58c017f36a1846dc6d03b76fba2226/src/TerraDevSite.jsx#L20)    I did edit the js code in the node_modules folder and confirmed setting the prop to true disables the alert popups.

Teams link:  https://teams.microsoft.com/l/message/19:0adf7161dd244f87aa6415f7c5577836@thread.skype/1574789498172?tenantId=fbc493a8-0d24-4454-a815-f4ca58e8c09d&groupId=45f47bfa-38a9-444d-8933-9c20266ae38c&parentMessageId=1574789498172&teamName=Terra&channelName=Component%20Support&createdTime=1574789498172

## Steps to Reproduce
1. Set up a wdio test that will render a component that renders a NavigationPrompt from terra-navigation-prompt. 
2. Call browser.url('your-url') in your test.
3.  The test will hang and timeout because the page cannot reload while there is an active alert popup.

## Additional Context / Screenshots
You can see the timeouts and that they are happening from an alert by setting logLevel to verbose in wdio.conf.js.

## Expected Behavior
We should not have alert boxes being generated by terra-dev-site as they are disruptive to test workflows and support for handling navigation prompts in wdio's framework is limited.  Disabling these popups in terra-dev-site wouldn't prevent consumers from rendering their own ApplicationBase and testing these alert popups if they need to test them.

## Possible Solution
Set unloadPromptIsDisabled={true} on the ApplicationBase component. https://github.com/cerner/terra-dev-site/blob/fa1700474d58c017f36a1846dc6d03b76fba2226/src/TerraDevSite.jsx#L20

## Environment
* Component Name and Version:  goals-js, healthconcerns-js, and plan-js
* Browser Name and Version:  Chrome
* Operating System and version (desktop or mobile): windows 10

**Comment by mjhenkes** [comment]
Terra dev site acts as a sample application, documentation site and a testing harness. As such, it needs to balance the needs of all three use cases. As people develop against the terra platform as defined by terra-application (The documentation can be found [here](https://engineering.cerner.com/terra-ui/components/terra-application/application/reference/components/application-base)) there is an expectation that it should behave and offer the same features as any terra application that the component could be embedded in. This includes all of the capabilities found in terra-application as well as the ability to launch a modal and more as we add them. Developers should not have to add these capabilities as they are part of the platform. From my perspective, having the unload prompt enabled by default is appropriate.

During testing it may not be desired to have dirty data launch an alert box and we don't want developers have to spend a lot of time debugging why their tests aren't working. I see a couple of options we could pursue

1. Clean up dirty data after a test run.
This is probably the most expedient solution for you right now, but doesn't solve the issue of other developers having to debug this issue.
2. Add an option to the dev-site config  to disable unload prompts
Dev-site today only allows one config for both testing and as a doc site, so you'd be disabling the prompt for all instances of the site. I think as part of this option we'd have to update dev site to allow a specified config file in some way.
3. Provide the ability to selectively disable the unload prompt per test case.
My favorite option, but we'd have to see if we could make this work. We'd have to find the right home for the mock prompt as we wouldn't want the examples to depend on dev-site.
4. Disable the unload prompt for all raw routes.
Using the same idea as above, what I don't like about this option is that the raw route would now function differently than the non raw route which could lead to confusion.

**Comment by po016255** [comment]
When a test fails on an alert, it isn't clear.  It simply hangs on the browser.url call that triggered the alert until it hits the max test timeout value.  Then it outputs BROWSER_TIMEOUT.  When the tests all eventually time out, it doesn't output the names of the tests that timed out. As far as I can tell, the only way to figure out the tests that fail is to set loglevel to verbose and look for the url that was loaded or add console statements to every test.

We can limit the time spent troubleshooting these issues and rewriting existing tests if we only enable these alerts for specific tests and not all tests.   We have views like create views that always render the navigation prompt, so undoing changes made to the data on screen isn't always an option.  We would have to rewrite the tests to test the parent of the view so that we would have a way to close the view.  Currently we render views directly in some tests when we want to just test the controls on them, that means they cannot be closed to get rid of the navigation prompt.

It makes more sense for us to make specific tests for these browser alerts by wrapping our component in ApplicationBase in the test file for those specific tests.

We also have tests that are passing in chrome, but they are all failing in IE.  When I manually run workflows in IE11 on the windows desktop I can trigger the alert and accept it as expected.  But when browser.acceptAlert is called in IE during wdio tests, I get the error 'No alert is active'.  I can run the tests one at a time and they pass, but when ran as a group the first test passes and the rest all fail with timeouts.  This behaves as if the alert did appear, but wasn't accepted causing the timeouts.
Was terra-application tested against the remote selenium grid for IE?  It appears only chrome was tested in the last wdio run and it wasn't using the selenium grid:  https://travis-ci.com/cerner/terra-application/jobs/263621619

**Comment by mjhenkes** [comment]
I'm going to put you down as a vote for option number 4.
I went with that in pr #226.
