### ISSUE TITLE
Main Tag is Not IE 10 Compatible  

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#221]
## Description
<main> tag is not supported in IE 10. We used it to wrap the raw routes: 

https://github.com/cerner/terra-dev-site/blob/master/src/raw/_Raw.jsx#L44 

## Steps to Reproduce

1. Open terra-ui.com on an IE 10 browser.
2. Look at console error.

## Additional Context / Screenshots
<img width="915" alt="Screen Shot 2019-12-03 at 4 12 59 PM" src="https://user-images.githubusercontent.com/14099737/70094287-d4cc2a00-15e7-11ea-84e8-53e4ef87fac6.png">

## Environment

* Browser Name and Version: IE 10

**Comment by nramamurth** [comment]
Dup of https://github.com/cerner/terra-framework/issues/780?

**Comment by ryanthemanuel** [comment]
See https://github.com/cerner/terra-framework/issues/780 for a discussion on this.
