### ISSUE TITLE
Questions Marks in MD Content Fails to Compile

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#225]
# Bug Report

## Description
Loading a markdown document into terra-dev-site that contains a question mark will throw:
```
ERROR in ./src/terra-dev-site/doc/Development.doc.md
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/toolkit/src/terra-dev-site/doc/Development.doc.md: Octal literal in strict mode (12:4304)
```

This is not an issue with `.mdx` extensions.

**Comment by mjhenkes** [comment]
@emilyrohrbough I can't recreate this. Could you provide more info?

**Comment by emilyrohrbough** [comment]
I can't reproduce the error either. This must have been me
