### ISSUE TITLE
Prevent secondary navigation jumping when selecting an item

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-dev-site#250]
# Bug

## Description
When a secondary navigation item already visible on screen is selected, it should not jump to the top of secondary navigation.

## Additional Context / Screenshots
![dev-site-nav-jump](https://user-images.githubusercontent.com/1588747/79466596-67cb9680-7fc2-11ea-9735-6401ee90d828.gif)

**Comment by pranav300** [comment]
Reopening this issue, as I missed a scenario where the item could be not visible but on top of the navigation menu.
