### ISSUE TITLE
Props Table Loader: Required custom prop showing as optional.

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-dev-site#275]
# Bug Report

## Description
This prop type:
```js
  /**
   * Internationalization object with translation APIs. Provided by `injectIntl`.
   */
  intl: intlShape.isRequired,
```
Renders as:
![Screen Shot 2020-06-04 at 9 33 10 AM](https://user-images.githubusercontent.com/1588747/83770217-6f183380-a646-11ea-84a1-3b159c108e6a.png)

## Steps to Reproduce
1. Setup a custom prop type
2. view it through the loader
3. 😭 
4.

## Expected Behavior
The prop should be listed as required.

## Possible Solution
🤷‍♂️ 

## Environment

* Component Name and Version:
* Browser Name and Version:
* Node/npm Version: [e.g. Node 8/npm 5]
* Webpack Version:
* Operating System and version (desktop or mobile):

**Comment by pranav300** [comment]
The reason behind it could be, when the loader sees a custom prop, it doesn't proceed further with the `isRequired` and makes it a not required prop.
Not completely but related to this thread: https://github.com/facebook/react/issues/9125.

**Comment by mjhenkes** [comment]
Lets to a little more checking on custom props to see if they are required.
Add logic [here abouts](https://github.com/cerner/terra-dev-site/blob/master/config/webpack/loaders/devSitePropsTable.js#L87) if the prop type is custom to check if the raw prop type ends with `.isRequired`. If so set is required to true.

Here's an example of what a custom prop looks like:
```js
PROP: { type: { name: 'custom', raw: 'intlShape.isRequired' },
  required: false,
  description:
   'Internationalization object with translation APIs. Provided by `injectIntl`.' }
```
