### ISSUE TITLE
[terra-dev-site] Missing themeable variables

### ISSUE THREAD

**Issue by ryanthemanuel** [cerner/terra-dev-site#280]
# Bug Report

The following themeable variables are missing:

**clinical-lowlight-theme**

--terra-dev-site-footer-background-color - lib/loader-components/ExampleTemplate.module.scss (line: 28, column: 4)
--terra-dev-site-header-background-color - lib/loader-components/ExampleTemplate.module.scss (line: 13, column: 4)
--terra-dev-site-marked-icon-link-background-image - lib/marked/marked.module.scss (line: 400, column: 4)
--terra-dev-site-template-content-background-color - lib/loader-components/ExampleTemplate.module.scss (line: 19, column: 4)

**orion-fusion-theme**

--terra-dev-site-blockquote-color - lib/mdx/MarkdownTags.module.scss (line: 28, column: 4)
--terra-dev-site-content-background-color - lib/wrappers/ContentLoaded.module.scss (line: 3, column: 4)
--terra-dev-site-footer-background-color - lib/loader-components/ExampleTemplate.module.scss (line: 28, column: 4)
--terra-dev-site-header-background-color - lib/loader-components/ExampleTemplate.module.scss (line: 13, column: 4)
--terra-dev-site-icon-link-background-image - lib/mdx/MarkdownTags.module.scss (line: 378, column: 4)
--terra-dev-site-layout-menu-panel-panel-background-color - lib/navigation/SecondaryNavigationLayout.module.scss (line: 22, column: 4)
--terra-dev-site-layout-menu-panel-panel-border-right - lib/navigation/SecondaryNavigationLayout.module.scss (line: 23, column: 4)
--terra-dev-site-marked-icon-link-background-image - lib/marked/marked.module.scss (line: 400, column: 4)
--terra-dev-site-template-content-background-color - lib/loader-components/ExampleTemplate.module.scss (line: 19, column: 4)

**Comment by jeremyfuksa** [comment]
**lowlight**
```
--terra-dev-site-footer-background-color: #004C76;
--terra-dev-site-header-background-color: #004C76;
--terra-dev-site-marked-icon-link-background-image: inline-svg('<svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" class="is-bidi icon icon-link"><path d="M10.5 26.3a16 16 0 0 1 .9-5.3L8 17.6a6.73 6.73 0 0 1-2-4.8A6.41 6.41 0 0 1 8 8a6.76 6.76 0 0 1 9.6 0l9 9a6.88 6.88 0 0 1 0 9.6 6.27 6.27 0 0 1-3.4 1.8 2.65 2.65 0 0 0 .5.6l4.1 4.1a11.36 11.36 0 0 0 3.1-2.3 12.8 12.8 0 0 0 0-18.1l-9-9a12.63 12.63 0 0 0-9-3.7 12.63 12.63 0 0 0-9 3.7A12.1 12.1 0 0 0 0 12.8a12.63 12.63 0 0 0 3.7 9l7 7a21.05 21.05 0 0 1-.2-2.5zm27-4.6a16 16 0 0 1-.9 5.3l3.4 3.4a6.79 6.79 0 1 1-9.6 9.6l-9-9a6.88 6.88 0 0 1 0-9.6 6.27 6.27 0 0 1 3.4-1.8 2.65 2.65 0 0 0-.5-.6l-4-4a11.36 11.36 0 0 0-3.1 2.3 12.8 12.8 0 0 0 0 18.1l9 9a12.73 12.73 0 0 0 18-18l-7-7a8 8 0 0 1 .3 2.3z"/></svg>');
--terra-dev-site-template-content-background-color: #1b2326;
```

**fusion**
```
--terra-dev-site-blockquote-color: #24292e;
--terra-dev-site-content-background-color: #fff;
--terra-dev-site-footer-background-color: #024979;
--terra-dev-site-header-background-color: #024979;
--terra-dev-site-icon-link-background-image: inline-svg('<svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" class="is-bidi icon icon-link"><path d="M10.5 26.3a16 16 0 0 1 .9-5.3L8 17.6a6.73 6.73 0 0 1-2-4.8A6.41 6.41 0 0 1 8 8a6.76 6.76 0 0 1 9.6 0l9 9a6.88 6.88 0 0 1 0 9.6 6.27 6.27 0 0 1-3.4 1.8 2.65 2.65 0 0 0 .5.6l4.1 4.1a11.36 11.36 0 0 0 3.1-2.3 12.8 12.8 0 0 0 0-18.1l-9-9a12.63 12.63 0 0 0-9-3.7 12.63 12.63 0 0 0-9 3.7A12.1 12.1 0 0 0 0 12.8a12.63 12.63 0 0 0 3.7 9l7 7a21.05 21.05 0 0 1-.2-2.5zm27-4.6a16 16 0 0 1-.9 5.3l3.4 3.4a6.79 6.79 0 1 1-9.6 9.6l-9-9a6.88 6.88 0 0 1 0-9.6 6.27 6.27 0 0 1 3.4-1.8 2.65 2.65 0 0 0-.5-.6l-4-4a11.36 11.36 0 0 0-3.1 2.3 12.8 12.8 0 0 0 0 18.1l9 9a12.73 12.73 0 0 0 18-18l-7-7a8 8 0 0 1 .3 2.3z"/></svg>');
--terra-dev-site-layout-menu-panel-panel-background-color: #fff;
--terra-dev-site-layout-menu-panel-panel-border-right: #d3d4d5;
--terra-dev-site-marked-icon-link-background-image: inline-svg('<svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" class="is-bidi icon icon-link"><path d="M10.5 26.3a16 16 0 0 1 .9-5.3L8 17.6a6.73 6.73 0 0 1-2-4.8A6.41 6.41 0 0 1 8 8a6.76 6.76 0 0 1 9.6 0l9 9a6.88 6.88 0 0 1 0 9.6 6.27 6.27 0 0 1-3.4 1.8 2.65 2.65 0 0 0 .5.6l4.1 4.1a11.36 11.36 0 0 0 3.1-2.3 12.8 12.8 0 0 0 0-18.1l-9-9a12.63 12.63 0 0 0-9-3.7 12.63 12.63 0 0 0-9 3.7A12.1 12.1 0 0 0 0 12.8a12.63 12.63 0 0 0 3.7 9l7 7a21.05 21.05 0 0 1-.2-2.5zm27-4.6a16 16 0 0 1-.9 5.3l3.4 3.4a6.79 6.79 0 1 1-9.6 9.6l-9-9a6.88 6.88 0 0 1 0-9.6 6.27 6.27 0 0 1 3.4-1.8 2.65 2.65 0 0 0-.5-.6l-4-4a11.36 11.36 0 0 0-3.1 2.3 12.8 12.8 0 0 0 0 18.1l9 9a12.73 12.73 0 0 0 18-18l-7-7a8 8 0 0 1 .3 2.3z"/></svg>');
--terra-dev-site-template-content-background-color: #fff;
```

**Comment by lokesh-0813** [comment]
@ryanthemanuel I have concerns regarding few variables with respect to folder structure.

I see the style files for themeable variables are not consistent with default theme. 

For instance `--terra-dev-site-blockquote-color` is in different place for orion and lowlight themes

```
-src
    |_ mdx
         |_ MarkdownTags.modules.scss
               |_ --terra-dev-site-blockquote-color
-
-
-
-themes
    |_ clinical-low-light-theme
         |_ clinical-low-light-theme.scss
              |_ --terra-dev-site-blockquote-color
```

I am not sure if `themes/clinical-low-light-theme/clinical-low-light-theme.scss` is called anywhere.

If the current hierarchy is right. I have a draft PR and will go ahead and make it ready for review. 

Also there is another variable missing for fusion theme `--terra-dev-site-themed-block-background-color'

**Comment by emilyrohrbough** [comment]
@lokesh-0813 The original theming strategy would aggregate themes via the [`tt-aggregate-themes` script](https://github.com/cerner/terra-toolkit-boneyard/tree/main/scripts/aggregate-themes) that is ran [before webpack in our webpack.config](https://github.com/cerner/terra-toolkit-boneyard/blob/main/config/webpack/webpack.config.js#L242). When this ran, it would search for themes in `themes/theme-name/theme-name.scss` and create an aggregated list that would be pulled in by webpack.

The [latest theme strategy](https://engineering.cerner.com/terra-ui/guides/terra-application/theme-strategy) will pull themes into the assets bundle via webpack without the need for `tt-aggregate-themes`. This follows the new structures `src/folder/styles.modules.scss` and `src/folder/theme-name/styles.modules.scss`. The theme imports the themes directly via the stylesheets and the ThemeContext is used to apply the correct theme to the component.

Once everything is using the new theme strategy, we should be able to remove tt-aggregate-themes. I think it we should be able to remove the `themes/` contents. We have been doing that in other places.

**Comment by jeremyfuksa** [comment]
For Fusion: `--terra-dev-site-themed-block-background-color: #0079be;`
