### ISSUE TITLE
Update browserslist-config-terra v1.2.0 to @cerner/browserslist-config-terra v^3.0.0 

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#285]
# Feature Request

## Description
We recently updated our browserslist config & released it as a scoped package. We should move to the latest version.

**Comment by andrewnottaviano** [comment]
I can pick this up.

**Comment by mjhenkes** [comment]
+1 It's similar https://github.com/cerner/terra-dev-site/pull/317 except on main instead of the v7 branch.

also instead of adding the `files` section the package.json add `.browserlistrc` to the `.npmignore`.
