### ISSUE TITLE
Add a Building a Site Guide

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#29]
# Issue Description
Documentation to include:

- Building a Site Using Terra-site
    - [x] A Minimalist Approach
    - [x] Custom App Configuration
    - [x] Component Configuration
    - [x] Custom Navigation Configuration
    - [ ] Custom Webpack Configuration
    - [ ] Custom Index
    - [ ] Custom Pages

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

**Comment by emilyrohrbough** [comment]
Progress on this issue can be followed in this branch: https://github.com/cerner/terra-site/tree/documentation.

**Comment by mjhenkes** [comment]
resolved
