### ISSUE TITLE
Provide a Component Site Page Template

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#33]
# Issue Description
Provide an component that will generate a consistent component documentation layout. It'd expect this to take 
- readme src
- component verison
- component src
- a list of example objects containing the example title and example src pairs

## Issue Type

- [x] New Feature
- [ ] Enhancement
- [ ] Bug
- [ ] Other

## Expected Behavior
Provides one place to mange, change and update the expected component index pages.

## Current Behavior
Right now, all Terra component documentation depends on the engineer writing the site index page to match the current layout. This results in inconsistent documentation provided, props-table and example layouts as well as doc styling.

**Comment by Blackop778** [comment]
# Tech Design for Site Layout
## Summary:
Creates one standardized layout for documentation pages with enough flexibility to suit one's needs.

## React Props:
| Prop     | Type | Default | Description  |
|----------|------|---------|--------------|
| version | string | '' | The page's component's current version |
| readme | string | '' | A markdown file containing the page's title, Getting Started section, Usage section, etc. |
| propsTables | array | {} |  An array of objects containing a `componentName` property for the Props Table title (which can be empty), a `componentSource` property for a raw import of the component's source code, and an optional `id` property specifying a CSS id for the PropsTable, forming an array with all the Props Tables for the page to display |
| examples | array | {} | An array of objects containing a `title` property with a title for the example, a `example` property containing a component to be displayed directly below the title, and an optional `id` property specifying a CSS id for the title element, forming an array with all the examples for the page to display |

## Example:
```
<SiteLayout
  version={version}
  readme={ReadMe}
  propsTables={{componentSource: {ButtonSrc}, id: "props"}}
  examples={{title: "Variant", example: <ButtonVariant />, id: "variant"},
      {title: "Block", example: <ButtonBlock />, id: "block"},
      {title: "Anchor", example: <ButtonAnchor />, id: "anchor"}}
/>
```

**Comment by emilyrohrbough** [comment]
I propose we rename this component. Possibly `SitePageTemplate` or `DocTemplate` or `SiteDocTemplate` or `PackageMarkdown`? I'm not sure on the name, but it should clearly indicate this is component creates a consistent layout for the package documentation.

- `propsTables` the should be set to default to `[]` for an empty array. 
- `examples` should also be set to `[]` for default. We should think on how we want to pull in these examples because we also want to display the example source code with each example. [Here is](https://github.com/cerner/terra-framework/blob/master/packages/terra-layout/examples/Index.site-page.jsx) an example of where we do this.

We can probably drop the ids in these configs. We don't really need the ids on these pages and we can use `component-name` and `title` to add unique identifiers.

**Comment by Blackop778** [comment]
`SiteDocTemplate` sounds like a good name. I'm certainly not sold on the current name.

We could use the `IndexPageTemplate` to display the examples and I think we'll have to just `!rawloader!` import the example code.

**Comment by mjhenkes** [comment]
A couple of comments:
I'd like the order of the docs to be:

1. version
2. readme
3. examples
4. props table

For examples I think we should add an optional `description` property in addition to the 'title' property to allow for further explanation of the example. 

I'd like to see the examples build in the code switching functionality by default.

Thinking further, I think eventually it would behoove us to provide a readme template as well, but we can think on that in the future.

**Comment by mjhenkes** [comment]
`SiteDocTemplate` 👍

**Comment by bjankord** [comment]
+1 on tech design.

**Comment by StephenEsser** [comment]
+1
