### ISSUE TITLE
Proposed rename to terra-doc-site.

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-dev-site#36]
# Issue Description
Concerns were raised from our leadership meeting that the name of terra-site could be confusing and that we should better indicate the intentions of terra-site to be a documentation site.

It was proposed that the name of the package be changed to `terra-doc-site`. We think this name better indicates that the package is intended to provide a documentation site.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [ ] Bug
- [x] Other

Does anyone have any other suggestions or concerns about re-naming?

**Comment by emilyrohrbough** [comment]
I agree, the name `terra-site` could be misleading as the site is intended to be an reusable site to show off UI components and house a consistent test setup for these components. It is not intended to be used as a starting block to build an entire application. 

That being said, given the fact we are also using terra-site to setup our tests, I would prefer if it was named something that encompasses site's entire intention (test examples see beyond the scope of just docs). Some name possibilities could be:

- `terra-exhibit`
- `terra-showroom`
- `terra-exhibit-application`
- `terra-inventory-site`
- `terra-directory-site`

**Comment by mjhenkes** [comment]
> terra-exhibit

![](https://i.imgflip.com/2541e1.jpg)

**Comment by mjhenkes** [comment]
I've tried to come up with some alternative names to terra-doc-site and my conclusion is that terra-doc-site is the least bad option. 
terra-site isn't as specific as would be desired to describe that this a framework, not a standalone site(I'm not sure framework is a good description either) to setup a doc and testing site.
terra-doc-site has the same framework problem as terra-site but at least describes that this is intended for doc (and testing?) sites.
terra-doc-framework, I'm not sure framework is the right descriptor for what this project does.

**Comment by bjankord** [comment]
+1 for terra-doc-site, I agree, it is the least bad option to describe this project of names we've come up with for it.

**Comment by mjhenkes** [comment]
I can take the first step towards this by simply renaming the repo. Can I get some more +1's on the new name `terra-doc-site` ? @emilyrohrbough @JakeLaCombe @ryanthemanuel

**Comment by emilyrohrbough** [comment]
+1 given we can't think of anything better. Its a 'middle-man' component that makes the naming hard.

**Comment by mjhenkes** [comment]
Had an in person meeting. The consensus was `terra-dev-site`

**Comment by mjhenkes** [comment]
closed with https://github.com/cerner/terra-dev-site/pull/39
