### ISSUE TITLE
Update terra-dev-site to webpack 4

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-dev-site#44]
# Issue Description
https://medium.com/webpack/webpack-4-released-today-6cdb994702d4
Imagine a day soon when we update webpack here and core, clinical, and framework all are upgraded at the same time.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

This change may be non-passive.

**Comment by emilyrohrbough** [comment]
https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

**Comment by mjhenkes** [comment]
resolved
