### ISSUE TITLE
full screen overlay partially hidden by side menu

### ISSUE THREAD

**Issue by zhongyn** [cerner/terra-dev-site#47]
# Issue Description
Using 2.0.0.-RC.6 terra-site in consumer-theme repo, fullscreen overlay looks like:

<img width="1388" alt="screen shot 2018-02-28 at 11 02 58 am" src="https://user-images.githubusercontent.com/5943136/36801351-7f55df5a-1c77-11e8-9983-05bf99a0481d.png">

**Comment by emilyrohrbough** [comment]
This is an issue with terra-overlay. See the logged issue [here](https://github.com/cerner/terra-core/issues/963). Once this bug is fixed, the latest terra-overlay version will need defined as the minimum to ensure this issue is resolved.

**Comment by noahbenham** [comment]
@emilyrohrbough Should this be closed?

**Comment by emilyrohrbough** [comment]
@noahbenham Technically this could be closed however I was going to keep it open for visibility for what appears to be site issues.

**Comment by emilyrohrbough** [comment]
Resolved in https://github.com/cerner/terra-core/pull/1955
