### ISSUE TITLE
Close Menu When Navigation is Selected on Mobile

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#48]
# Issue Description
On Mobile the hover menu currently remains open when a new link is selected. The site behaves as expected, but it would be nice if on mobile devices this would automatically close to show the content.

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by mjhenkes** [comment]
Resolved
