### ISSUE TITLE
Theming Plugin Generates Incomplete Set of Themeable Variables 

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#54]
This issue is moved from https://github.com/cerner/terra-core/issues/1238.

# Issue Description

When running `npm start`, it appears the theming plugin is generating an incomplete set of themable variables in `packages/terra-site/themeable-variables.json`

My thought is this could be a result of use switching to a CSS custom property syntax that doesn't provide fallback values. Its odd that it is just now showing up.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
`packages/terra-site/themeable-variables.json` contains full set of themable variables in terra-core

## Current Behavior
`packages/terra-site/themeable-variables.json` contains only themable variables for ButtonGroupButton

## Steps to Reproduce

1. Run clean install on master branch
2. Run npm start
3. View `packages/terra-site/themeable-variables.json` 

## Environment

* Component Version: terra-core-site: 2.0.0
* Browser Name and Version: N/A
* Operating System and version (desktop or mobile): N/a

**Comment by emilyrohrbough** [comment]
I am wondering if the theming plugin step should only be run and deployment builds. The themable variable list is useful, however, when running webpack locally, if the latest component versions are not installed, the list results in changes.

**Comment by emilyrohrbough** [comment]
It appears the themeing plugin is grabbing theming default values set in the tests. See https://github.com/cerner/terra-core/pull/1367#discussion_r178335407

**Comment by bjankord** [comment]
Closing as we no longer use this plugin and it was only for internal usage amongst the terra repos.
