### ISSUE TITLE
Caret for settings menu doesn't rotate appropriately.

### ISSUE THREAD

**Issue by JakeLaCombe** [cerner/terra-dev-site#72]
# Issue Description
The caret for the settings dropdown should point up when clicked, but it always points down.

## Issue Type

- [ ] New Feature
- [ ] Enhancement
- [x] Bug
- [ ] Other

## Expected Behavior
Caret rotates appropriately when menu is opened vs closed.

## Current Behavior
Caret does no rotating.

<img width="124" alt="screen shot 2018-04-19 at 2 54 43 pm" src="https://user-images.githubusercontent.com/2552573/39015114-fdc22b78-43e1-11e8-9b08-b1b6a1a67709.png">
<img width="165" alt="screen shot 2018-04-19 at 2 54 46 pm" src="https://user-images.githubusercontent.com/2552573/39015120-0200d43c-43e2-11e8-961f-3adbaee1b92b.png">

**Comment by emilyrohrbough** [comment]
@JakeLaCombe This should be logged as a bug for terra-application-utility in the framework repo.

**Comment by emilyrohrbough** [comment]
Yeah it gets a bit fuzzy. 😄At this point, almost all of terra-dev-site is supplied via terra-application-layout and configuration. 

See https://github.com/cerner/terra-framework/issues/158 for information regarding this issue. Will close this issue once resolved in terra-framework.

**Comment by JakeLaCombe** [comment]
Since we closed in the terra-framework as not applicable, we can close this
