### ISSUE TITLE
Add terra-base alias to webpack config

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#83]
# Issue Description
Terra components have been declaring terra-base as a dependency and a peer dependency. We should move this to be a peer dependency to ensure only one version is installed and referenced. 

Doing this, we should add a terra-base alias to the webpack config: https://github.com/cerner/terra-toolkit/blob/master/config/webpack/webpack.config.js#L97

## Issue Type

- [ ] New Feature
- [x] Enhancement
- [ ] Bug
- [ ] Other

**Comment by mjhenkes** [comment]
@emilyrohrbough do we want to add it to terra-dev-site or to terra-toolkit?

**Comment by mjhenkes** [comment]
N/A
