### ISSUE TITLE
Search Nested Test Dirs in generate-component-config

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/terra-dev-site#9]
# Issue Description
Currently the default search patterns does not allow for 
```
component
    /examples
       /test-examples
           /subcomponent
```

Initially did not allow for this given some components need test-content. I propose we decided on a "blacklisted" subdir to dump test content in and then search sub dirs.

**Comment by emilyrohrbough** [comment]
Talked offline with @mjhenkes @tbiethman & @dkasper-was-taken. It was decided to default the search paths to use `.example.jsx` indicators to allow for more flexible file structure. This will be non-passive.

**Comment by mjhenkes** [comment]
We discussed and like the idea of adding an extension of .example to any component intended to be displayed as a test example

For example: `AggregatorInModal.example.jsx`
