### ISSUE TITLE
Redirected navigational pages do not auto close the side menu on mobile.

### ISSUE THREAD

**Issue by mjhenkes** [cerner/terra-dev-site#92]
# Bug Report

## Description
Terra dev site will automatically redirect to the first menu item without children. If an item was selected directly the menu would automatically close. In this case I think an argument could be made to either close the menu or leave it up to user action to close. Auto closing the menu would be more consistent with existing interactions, but may harm discoverability of the additional menu items.

## Steps to Reproduce
1. On a site using terra-dev-site, navigate into a menu item containing a menu item with no child items.

## Additional Context / Screenshots
![screen recording 2018-07-10 at 08 13 am](https://user-images.githubusercontent.com/1588747/42512123-671d71f0-8419-11e8-9e38-0c8971bf9b40.gif)

## Expected Behavior
I'm not sure. Either leave as-is or close the menu on a redirect.

## Possible Solution
We could wrap the redirect component with one that first closes the menu then redirects.

**Comment by bjankord** [comment]
Talked with @mmalaker about this and we're of the opinion it should close the menu on a redirect.

**Comment by mjhenkes** [comment]
Discussed this issue in length with UX. The current recommedation is to **not** auto redirect to the first menu item on mobile and instead require the user to select the item they want. I have a prototype of this and should be able to get a pr up later today*.

*Today may not mean today
