### ISSUE TITLE
Add support for TypeScript in generatePagesConfig

### ISSUE THREAD

**Issue by dv297** [cerner/terra-dev-site#98]
# Feature Request
terra-dev-site doesn't currently allow TypeScript files. The new feature would either be...
* Add TS/TSX as extensions called out in generatePagesConfig.js
* Add a way to configure which extensions to include in the terra-dev-site

## Description
generatePagesConfig has three lines that explicitly reference typical JS-file extensions.

https://github.com/cerner/terra-dev-site/blob/v2.1.0/scripts/generate-app-config/generatePagesConfig.js#L127
https://github.com/cerner/terra-dev-site/blob/v2.1.0/scripts/generate-app-config/generatePagesConfig.js#L202-L206

This creates an issue for TypeScript projects because terra-dev-site won't recognize the TypeScript files as components to include on the terra-dev-site and just shows an empty component page. Although Terra doesn't explicitly support TypeScript, it would be nice if terra-dev-site didn't necessarily block TypeScript, especially since terra-toolkit already has all the configuration and doc to allow custom Webpack configs and thus TypeScript.

**Comment by mjhenkes** [comment]
I'm open to adding a way to configure extensions to include in terra-dev-site.

**Comment by mjhenkes** [comment]
Resolved in PR #202. We didn't explicitly add support for type script but we now look at the webpack resolve extensions field for the file extensions that we pull into dev site so dev site should 'just work' with the existing typescript webpack setups people have.
